debug: false
uuid: 0ae608b1-317f-4076-b21f-a6a9ff5b7ed9
token_id: 3buEQ05XPWb9ls4O
token: Y1vhHzjzOt9p2kEP3FJPHZA3adTflKOJyBUNRorr9D4bxqKd2TSKL5pZHbcGvE2J
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/reptile-present-fish.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/reptile-present-fish.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://cuddly-halibut-7x6wxrqxgjp3wp7x-80.app.github.dev'
