debug: false
uuid: 626c38cb-b010-4c35-9b34-3eea003e9a4c
token_id: medj0ppES2EYqH2W
token: 2lztkjuvcO2pgxtLWUQ5Yayv0738svcMoVoswkNy0BlFqhbuzn1d59VdMVdpFE0H
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/lemming-deciding-reindeer.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/lemming-deciding-reindeer.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://potential-acorn-v59w5g47gv5cxpqg-80.app.github.dev'
