debug: false
uuid: cf910057-2599-4300-b82e-fe7e01c5401d
token_id: 21C4ToXfaKUL00wh
token: x1r2JlwkHer4CbXSQhlr2UpTx9MjkgLfEWlKvstFiKFKa0j7MiCiNQLINHKA8fJG
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/whale-cute-slightly.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/whale-cute-slightly.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://humble-space-invention-7x6wxrqxg5jcppqr-80.app.github.dev'
