debug: false
uuid: ab371edc-0015-4c23-af1c-c44dfbf972fc
token_id: He6geZyLQwPqhUxr
token: kuiY4LkfewRkXHiX0O2wDtyvxJlYcCIS0sheXS5CTG3OFQyD2Lfde2aXLomsjSI6
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/stunning-space-spoon-qxj6x9rg7wqcxgq5-443.app.github.dev/fullchain.pem
    key: /etc/letsencrypt/live/stunning-space-spoon-qxj6x9rg7wqcxgq5-443.app.github.dev/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://humble-space-invention-7x6wxrqxg5jcppqr-80.app.github.dev'
