debug: false
uuid: f3ab7b1d-3d5a-479f-b300-fd5e1fcc46ad
token_id: od1Lon6laPNS32hY
token: OPCJ4bHbPRo5nBNN7Rs6ACQglQjns3P2Aincz3UNhdmSMnOBe1rnnIt6ONo9OZdq
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/whale-cute-slightly.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/whale-cute-slightly.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://orange-waddle-7x6wxrq4rw73x7v7-80.app.github.dev'
