debug: false
uuid: d1132c72-b110-4f22-a056-4a4ac0b0abdc
token_id: dXkRDvRYP7bdccLL
token: maNdqOq0hEbZdQyeIhoaxNqUXtEVoISOTYbD1RTHtyyil4RgJPY92EwbKMyEa8ec
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/flexible-uniquely-hornet.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/flexible-uniquely-hornet.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://kepriweb-1.duckdns.org'
