debug: false
uuid: 13d25947-7ba2-4a23-8ace-2b2368c2bc98
token_id: 0wfagccqwkpjLU4m
token: BU2MWNQDOcjUDccQZnK2vIwEtO5azfLZupliaIK2cJvll5MaDJxu8lK4rb8UGYl5
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/fictional-couscous-x47x496q9gpfpj79-443.app.github.dev/fullchain.pem
    key: /etc/letsencrypt/live/fictional-couscous-x47x496q9gpfpj79-443.app.github.dev/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://fictional-couscous-x47x496q9gpfpj79-80.app.github.dev'
